export const listRegion = [
  {
    name: "us-east-1",
    value: "us-east-1",
  },
  { name: "us-east-2", value: "us-east-2" },
  { name: "us-west-1", value: "us-west-1" },
  { name: "us-west-2", value: "us-west-2" },
  { name: "af-south-1", value: "af-south-1" },
  { name: "ap-east-1", value: "ap-east-1" },
  { name: "ap-south-1", value: "ap-south-1" },
  { name: "ap-southeast-1", value: "ap-southeast-1" },
  { name: "ap-southeast-2", value: "ap-southeast-2" },
  { name: "ap-northeast-1", value: "ap-northeast-1" },
  { name: "ap-northeast-2", value: "ap-northeast-2" },
  { name: "ap-northeast-3", value: "ap-northeast-3" },
  { name: "ca-central-1", value: "ca-central-1" },
  { name: "eu-central-1", value: "eu-central-1" },
  { name: "eu-west-1", value: "eu-west-1" },
  { name: "eu-west-2", value: "eu-west-2" },
  { name: "eu-west-3", value: "eu-west-3" },
  { name: "eu-south-1", value: "eu-south-1" },
  { name: "eu-north-1", value: "eu-north-1" },
  { name: "me-south-1", value: "me-south-1" },
  { name: "sa-east-1", value: "sa-east-1" },
  { name: "cn-north-1", value: "cn-north-1" },
  { name: "cn-northwest-1", value: "cn-northwest-1" },
  { name: "us-gov-east-1", value: "us-gov-east-1" },
  { name: "us-gov-west-1", value: "us-gov-west-1" },
];
